### ISSUE TITLE
Handle highways completely dedicated for bus ?

### ISSUE THREAD

**Issue by nlehuby** [zetx16/bus-lanes#2]
I cannot see or edit some ways that are completely dedicated for bus.
For instance here:
![image](https://user-images.githubusercontent.com/919962/68469614-cbcf7f00-021a-11ea-8ab6-6636b2197241.png)

it is tagged with 
* highway=service
* psv = yes
* access = no

**Comment by zlant** [comment]
I have not considered such cases. Someday I will try to add their support.

**Comment by nlehuby** [comment]
I may be able to help, if you give me some guidance.
